### ISSUE TITLE
NPC Skill on https://tk20466.github.io/ wrong!

### ISSUE THREAD

**Issue by tiagoratto** [TK20466/RPG-Web-Components#1]
First of all, nice work!

Well, on the NPC example shown on https://tk20466.github.io/, you made him have 2 Agility and 4 Ranged Light, that would result in four dices, 2 green and 2 yellow (4 from the Skill, since it's greater that it's parent characteristic, and 2 yellow from the Agility characteristic), not in three yellow as it's there.

**Comment by TK20466** [comment]
Confirmed.  Problem with developer's understanding of how to upgrade dice.

**Comment by tiagoratto** [comment]
I was looking in how the books represent the dices and it seems that they treat like GGYY instead of YYGG.

**Comment by TK20466** [comment]
I've been using Operation Shadowpoint PDF as my guide baseline.  They show upgraded dice as (Y)(G) format:  https://images-cdn.fantasyflightgames.com/filer_public/de/74/de74406e-2f92-49bf-9e47-1c4b9831a825/swap01operationshadowpointwq.pdf

What source is showing it as (G)(Y)?
