### ISSUE TITLE
Table Spacers Style

### ISSUE THREAD

**Issue by TK20466** [TK20466/RPG-Web-Components#10]
Need to add a style rule for sub heading rows... example from AoR core:
![image](https://cloud.githubusercontent.com/assets/26286647/24721991/08d075ee-1a10-11e7-8abe-86f3d9b31bb7.png)

**Comment by jonroost** [comment]
Don't know if it helps, but I added it for my personal site with just adding the following code to the CSS:
`.tablecat {color: #fff; background: #000; font-weight: bold;}`
And then for that row just setting the cell to span all of the columns. Hope that helps!

**Comment by TK20466** [comment]
Thanks Jonroost!  That looks about right :) just need to decide on a class name
