### ISSUE TITLE
Gulp 4 compatibility

### ISSUE THREAD

**Issue by Triarier** [TK20466/RPG-Web-Components#12]
It seems to not work with current version of gulp 4.
I downgraded to gulp 3.9.1 

If I made no mistake, it would be nice to extend the Readme or gulpfile, since I did not see any hints of not working with gulp4.

**Comment by TK20466** [comment]
Fixed with https://github.com/TK20466/RPG-Web-Components/commit/1335fdaf5af789ca4528aebb077a71ee25b28457

Gulp 4 is now supported
