### ISSUE TITLE
Image as background

### ISSUE THREAD

**Issue by n1c0x** [TK20466/RPG-Web-Components#22]
Hello, 
I like your template. I saw [this page](http://swrpg.sarah-bailey.com/Dark%20Hammer/The%20Crimson%20Jewel). How do you make this kind of design, with the background on all the width, the typo color and the image of the planet ? 

Thanks. 

Regards.

**Comment by TK20466** [comment]
Hey!  Sorry for taking TWO YEARS to reply to this haha.  The link is now here:  http://swrpg.ezrabailey.net/Dark%20Hammer/The%20Crimson%20Jewel

I created the following in my markup:

`<section id="gromas" class="starfield">
    <img src="/images/gromas.png" style="shape-outside: url(/images/gromas.png)">
    <h2>Gromas System</h2>
    <br />
    <p><b>Astrogation Data:</b> Gromas system, Perkell Sector,
    Mid Rim</p>
    <p><b>Orbital Metrics:</b> 700 days per year/20 hours per
    day</p>
    <p><b>Government:</b> Democratic</p>
    <p><b>Population:</b> 500 million (humans 63%, other 37%)</p>
    <p><b>Languages:</b> Basic</p>
    <p><b>Terrain:</b> Varies by moon</p>
    <p><b>Major Cities:</b> Gromas Prime/Arris, Gromas Prime/Noku</p>
    <p><b>Areas of Interest:</b> Government district in Arris, Felth Mines on Gromas 16</p>
    <p><b>Major Exports:</b> Duralloy ore</p>
    <p><b>Major Imports:</b> foodstuffs, water</p>
    <p><b>Trade Routes:</b>Perlemian Trade Route</p>
    <p><b>Special Conditions:</b> Large amounts of debris is orbit.</p>
    <p><b>Background:</b> The <b>Gromas</b> system.....</p>
</section>`

Then created these custom styles for the section:

`section.starfield {
  background-image: url(/images/starfield.png);
  color: #99c1da;
  width: 100%;
  margin-left: -12.5%;
  padding-left: 12.5%;
  padding-right: 12.5%;
  padding-top: 5%;
  padding-bottom: 5%;
}

section.starfield h2 {
  color: white;
}

section.starfield img {
  float: right;
  width: 35%;
  min-width: 300px;
  margin-right: 15%;
  shape-image-threshold: 0.5;
}`

The images were just made in photoshop; feel free to use both or make your own:
http://swrpg.ezrabailey.net/images/gromas.png
http://swrpg.ezrabailey.net/images/starfield.png

You might have to play around with CSS a little depending on the image over the Starfield.  This is jsut general custom markup, not something this system "supports" per se

**Comment by n1c0x** [comment]
Hello, 
Thank you for your feedback, even after a so long time. 
I will try this.
