### ISSUE TITLE
Use relative rather than absolute URLs in CSS reference

### ISSUE THREAD

**Issue by chrisfarnham** [TK20466/RPG-Web-Components#7]
If I reference your component as a package then it has a different absolute path within the project.

bower.json
```
{
  "name": "angular-seed",
  "description": "A starter project for AngularJS",
  "version": "0.0.0",
  "homepage": "https://github.com/angular/angular-seed",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "angular": "~1.5.0",
    "angular-route": "~1.5.0",
    "angular-loader": "~1.5.0",
    "angular-mocks": "~1.5.0",
    "html5-boilerplate": "^5.3.0",
    "swaor": "https://github.com/TK20466/RPG-Web-Components/releases/download/v0.9.4/0.9.4.zip"
  }
}
```
Then the component would be at path: `bower_components/swaor/` and the css reference would look like this: `<link rel="stylesheet" href="bower_components/swaor/styles/swrpgaor.min.css">`.

But then there are 404s for some assets :( 

![screen shot 2017-03-22 at 5 19 31 pm](https://cloud.githubusercontent.com/assets/680287/24221219/d244871e-0f23-11e7-9950-3047c6abd19d.png)

This might be fixed by using relative paths: http://stackoverflow.com/questions/5815452/how-to-use-relative-absolute-paths-in-css-urls

**Comment by TK20466** [comment]
I'll get this in over the weekend :)

**Comment by TK20466** [comment]
Should be good now.  This will be included in the next release.
